name: CI - Test&Build
on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: LV20x64
    steps:
      - uses: actions/checkout@v3
      - name: Test g-cli
        shell: bash
        run: ./run_test.sh

